server/config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :monsters
  get 'games/index'
  get 'games/state'
  get 'games/play_card'
  get '/', to: 'static_pages#home', as: 'home'
  get 'static_pages/help'
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

server/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

server/app/models/card.rb
class Card < ApplicationRecord  
	def self.cardTypes
    [['Attack', 1], ['Defense', 2]]
  end

  def self.cardImages
  	{ 1=> "Sword.png", 2 => "Defense.png"}
  end
end

server/app/models/game.rb
class Game < ApplicationRecord
  has_many :players, dependent: :destroy

  def play_card(player_id, card_id, slot_id)
    card = players[player_id.to_i].cards[card_id.to_i]
    card.played_in = slot_id.to_i
    card.save
  end

  def to_dto
    dto = {}
    dto['play_slots'] = build_play_slots
    dto['players'] = []
    players.each do |player|
      dto['players'].push player.to_dto
    end
    dto
  end

  def build_play_slots
    [
      card_in_slot(0),
      card_in_slot(1),
      card_in_slot(2),
      card_in_slot(3)
    ]
  end

  def card_in_slot(slot)
    players.each do |player|
      player.cards.each do |card|
        return card.to_dto if card.played_in == slot
      end
    end
    nil
  end
end

server/app/models/game_creator.rb
class GameCreator
  def self.last
    if Game.exists?(1)
      game = Game.includes(players: [:cards]).last
      game
    else
      GameCreator.build
    end
  end

  def self.build
    game = Game.create
    4.times do |num|
      name = "player#{num}"
      player = game.players.create(name: name)
      4.times do |cnum|
        player.cards.create(name: "#{name}card#{cnum}")
      end
    end
    game
  end
end

server/app/models/game_state.rb
class GameState
  def initialize
    @hands = []
    4.times do |num|
      @hands << Hand.new("player#{num}")
    end
  end

  attr_reader :hands
end

server/app/models/hand.rb
class Hand
  def initialize(player_name)
    @player_name = player_name
    @cards = []
    4.times do |num|
      @cards << PlayableCard.create(name: "#{player_name}card#{num}")
    end
  end

  attr_reader :cards
  attr_reader :player_name
end

server/app/models/monster.rb
class Monster < ApplicationRecord
end

server/app/models/playable_card.rb
class PlayableCard < ApplicationRecord
  def as_json(options = {})
    super(options.merge(only: :name))
  end

  def to_dto
    cdto = {}
    cdto['name'] = name
    cdto
  end

  belongs_to :player, inverse_of: :cards
end

server/app/models/player.rb
class Player < ApplicationRecord
  def as_json(options = {})
    super(options.merge(only: :name))
  end

  def to_dto
    pdto = {}
    pdto['name'] = name
    pdto['cards'] = []
    cards.each do |card|
      pdto['cards'].push card.played_in ? nil : card.to_dto
    end
    pdto
  end

  belongs_to :game, inverse_of: :players
  has_many :cards, class_name: 'PlayableCard', dependent: :destroy
end

server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def index
    render html: 'project super great!'
  end
end

server/app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_card
    @card = Card.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def card_params
    params.require(:card).permit(:name, :character, :card_type, :effect)
  end
end

server/app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @state = GameCreator.last
  end

  def state
    respond_to :json
    game = GameCreator.last
    render json: game.to_dto
  end
end

server/app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :set_monster, only: [:show, :edit, :update, :destroy]

  # GET /monsters
  # GET /monsters.json
  def index
    @monsters = Monster.all
  end

  # GET /monsters/1
  # GET /monsters/1.json
  def show
  end

  # GET /monsters/new
  def new
    @monster = Monster.new
  end

  # GET /monsters/1/edit
  def edit
  end

  # POST /monsters
  # POST /monsters.json
  def create
    @monster = Monster.new(monster_params)

    respond_to do |format|
      if @monster.save
        format.html { redirect_to @monster, notice: 'Monster was successfully created.' }
        format.json { render :show, status: :created, location: @monster }
      else
        format.html { render :new }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monsters/1
  # PATCH/PUT /monsters/1.json
  def update
    respond_to do |format|
      if @monster.update(monster_params)
        format.html { redirect_to @monster, notice: 'Monster was successfully updated.' }
        format.json { render :show, status: :ok, location: @monster }
      else
        format.html { render :edit }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monsters/1
  # DELETE /monsters/1.json
  def destroy
    @monster.destroy
    respond_to do |format|
      format.html { redirect_to monsters_url, notice: 'Monster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_monster
    @monster = Monster.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def monster_params
    params.require(:monster).permit(:name, :health, :attack, :defense, :effect)
  end
end

server/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

server/app/helpers/application_helper.rb
module ApplicationHelper
end

server/app/helpers/cards_helper.rb
module CardsHelper
end

server/app/helpers/games_helper.rb
module GamesHelper
end

server/app/helpers/monsters_helper.rb
module MonstersHelper
end

server/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

server/app/views/cards/_form.html.erb
<%= form_for(card) do |f| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :character %>
    <%= f.text_field :character %>
  </div>

  <div class="field">
    <%= f.label :card_type %>
    <%= f.select :card_type, options_for_select(Card.cardTypes, card.card_type) %>
  </div>

  <div class="field">
    <%= f.label :effect %>
    <%= f.text_field :effect %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

server/app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Character</th>
      <th>Card type</th>
      <th>Effect</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="cardList">
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.name %></td>
        <td><%= card.character %></td>
        <td><%= card.card_type %><%= image_tag(Card.cardImages[card.card_type]) %></td>
        <td><%= card.effect %></td>
        <td><%= link_to 'Show', card %>
            <%= link_to 'Edit', edit_card_path(card) %>
            <%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

server/app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

server/app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @card.name %>
</p>

<p>
  <strong>Character:</strong>
  <%= @card.character %>
</p>

<p>
  <strong>Card type:</strong>
  <%= @card.card_type %>
</p>

<p>
  <strong>Effect:</strong>
  <%= @card.effect %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

server/app/views/games/_player_card.html.erb
<% if @state.players[player].cards[card] %>
<div id=<%= "p" + player.to_s + "card" + card.to_s %> class="card" draggable="true" data-player=<%=player%> data-card=<%=card%>>
	<%= @state.players[player].cards[card].name %>
</div>
<% else %>
<div class="card-slot"></div> 
<% end %>

server/app/views/games/index.html.erb
<% provide(:title, "Playing a game") %>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-5"></div>
		<div class="col-md-1"><div id="monster-card" class="card">monster area</div></div>
		<div class="col-md-5"></div>
	</div>
	<div class="row">
		<div class="col-md-1"></div>
		<div class="col-md-1">
			<%= render partial: "player_card", locals: {player: 0, card: 0} %>
		</div>
		<div class="col-md-3"></div>
		<div class="col-md-1"><div id="playslot0" class="card-slot" data-slot="0">1st position</div></div>
		<div class="col-md-3"></div>
		<div class="col-md-1">
			<%= render partial: "player_card", locals: {player: 1, card: 0} %>
		</div>
		<div class="col-md-1"></div>
	</div>
	<div class="row">
		<div class="col-md-1"></div>
		<div class="col-md-1">
			<%= render partial: "player_card", locals: {player: 0, card: 1} %>
		</div>
		<div class="col-md-3"></div>
		<div class="col-md-1"><div id="playslot1" class="card-slot" data-slot="1">2nd position</div></div>
		<div class="col-md-3"></div>
		<div class="col-md-1">
			<%= render partial: "player_card", locals: {player: 1, card: 1} %>
		</div>		
		<div class="col-md-1"></div>
	</div>
	<div class="row">
		<div class="col-md-1"></div>
				<div class="col-md-1">
			<%= render partial: "player_card", locals: {player: 0, card: 2} %>
		</div>	
		<div class="col-md-3"></div>
		<div class="col-md-1"><div id="playslot2" class="card-slot" data-slot="2">3rd position</div></div>
		<div class="col-md-3"></div>
		<div class="col-md-1">
			<%= render partial: "player_card", locals: {player: 1, card: 2} %>
		</div>	
		<div class="col-md-1"></div>
	</div>
	<div class="row">
		<div class="col-md-1"></div>
		<div class="col-md-1">
			<%= render partial: "player_card", locals: {player: 0, card: 3} %>
		</div>	
		<div class="col-md-3"></div>
		<div class="col-md-1"><div id="playslot3" class="card-slot" data-slot="3">4th position</div></div>
		<div class="col-md-3"></div>
		<div class="col-md-1">
			<%= render partial: "player_card", locals: {player: 1, card: 3} %>
		</div>	
		<div class="col-md-1"></div>
	</div>
	<br/>
	<div class="row">
		<div class="col-md-1"></div>
		<div class="col-md-1"><%= render partial: "player_card", locals: {player: 2, card: 0} %></div>
		<div class="col-md-1"><%= render partial: "player_card", locals: {player: 2, card: 1} %></div>
		<div class="col-md-1"><%= render partial: "player_card", locals: {player: 2, card: 2} %></div>
		<div class="col-md-1"><%= render partial: "player_card", locals: {player: 2, card: 3} %></div>
		<div class="col-md-1"></div>
		<div class="col-md-1"><%= render partial: "player_card", locals: {player: 3, card: 0} %></div>
		<div class="col-md-1"><%= render partial: "player_card", locals: {player: 3, card: 1} %></div>
		<div class="col-md-1"><%= render partial: "player_card", locals: {player: 3, card: 2} %></div>
		<div class="col-md-1"><%= render partial: "player_card", locals: {player: 3, card: 3} %></div>
		<div class="col-md-1"></div>
	</div>
</div>

server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Project Super Great!</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

server/app/views/monsters/_form.html.erb
<%= form_for(monster) do |f| %>
  <% if monster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(monster.errors.count, "error") %> prohibited this monster from being saved:</h2>

      <ul>
      <% monster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :health %>
    <%= f.text_field :health %>
  </div>

  <div class="field">
    <%= f.label :attack %>
    <%= f.text_field :attack %>
  </div>

  <div class="field">
    <%= f.label :defense %>
    <%= f.text_field :defense %>
  </div>

  <div class="field">
    <%= f.label :effect %>
    <%= f.text_field :effect %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/monsters/edit.html.erb
<h1>Editing Monster</h1>

<%= render 'form', monster: @monster %>

<%= link_to 'Show', @monster %> |
<%= link_to 'Back', monsters_path %>

server/app/views/monsters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Monsters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Health</th>
      <th>Attack</th>
      <th>Defense</th>
      <th>Effect</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="cardList">
    <% @monsters.each do |monster| %>
      <tr>
        <td><%= monster.name %></td>
        <td><%= monster.health %></td>
        <td><%= monster.attack %></td>
        <td><%= monster.defense %></td>
        <td><%= monster.effect %></td>
        <td><%= link_to 'Show', monster %>
            <%= link_to 'Edit', edit_monster_path(monster) %>
            <%= link_to 'Destroy', monster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Monster', new_monster_path %>

server/app/views/monsters/new.html.erb
<h1>New Monster</h1>

<%= render 'form', monster: @monster %>

<%= link_to 'Back', monsters_path %>

server/app/views/monsters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @monster.name %>
</p>

<p>
  <strong>Health:</strong>
  <%= @monster.health %>
</p>

<p>
  <strong>Attack:</strong>
  <%= @monster.attack %>
</p>

<p>
  <strong>Defense:</strong>
  <%= @monster.defense %>
</p>

<p>
  <strong>Effect:</strong>
  <%= @monster.effect %>
</p>

<%= link_to 'Edit', edit_monster_path(@monster) %> |
<%= link_to 'Back', monsters_path %>

server/app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help!</h1>
<p>This isn't necessary!</p>

server/app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>Project Super Great!</h1>
<p>Server for project super great!</p>
<%= link_to "Play a game", games_index_url %>
<br/>
<%= link_to "View and edit cards", cards_path %>
<br/>
<%= link_to "View and edit monsters", monsters_path %>